// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc.team3824.robot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainDriveMotorLeft;
    public static SpeedController driveTrainDriveMotorRight;
    public static RobotDrive driveTrainRobotDrive;
    public static Solenoid driveTrainShifter;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainDriveMotorLeft = new Victor(0);
	LiveWindow.addActuator("DriveTrain", "DriveMotorLeft", (Victor) driveTrainDriveMotorLeft);
        
        driveTrainDriveMotorRight = new Victor(1);
	LiveWindow.addActuator("DriveTrain", "DriveMotorRight", (Victor) driveTrainDriveMotorRight);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainDriveMotorLeft, driveTrainDriveMotorRight);
	
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        
        driveTrainShifter = new Solenoid(0, 0);
	LiveWindow.addActuator("DriveTrain", "Shifter", driveTrainShifter);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
