// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc.team3824.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc.team3824.robot.subsystems.*;
import org.usfirst.frc.team3824.robot.Robot;
/**
 *
 */
public class  CmdShfitHigh extends Command {
    public CmdShfitHigh() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	Robot.driveTrain.getShifter().set(false);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    	// Shift up into high gear
    	Robot.driveTrain.getShifter().set(true);
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false; //!super.isRunning();
    }
    // Called once after isFinished returns true
    protected void end() {
    	// Shift down to low gear
    	//Robot.driveTrain.getShifter().set(false);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.driveTrain.getShifter().set(false);
    }
}
